/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;
import GUI.MenuAnimales.MenuAnimales;
import GUI.Presentaciones.InicioTrabajador;
import GUI.Presentaciones.InicioConsultor;
import GUI.Presentaciones.InicioCampesino;
import Classes.User.Campesino;
import Classes.User.TemaUNCampesino;
import Classes.User.Usuario;
import GUI.MenuCultivos.MenuCultivos;
import GUI.MenuProductos.ProductosCompra;
import GUI.MenuProductos.productosCRUD;
import GUI.MenuTareas.MenuTareas;
import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import javax.imageio.ImageIO;
import static uncampesino.UNCampesino.gestorUsuarios;
import static uncampesino.UNCampesino.mainMenu;
import static uncampesino.UNCampesino.menuCampesino;
import static uncampesino.UNCampesino.menuConsultores;
/**
 *
 * @author yesid
 */
public class PagPrincipal extends javax.swing.JFrame {
    public boolean ingresado =false;
    public static final Usuario USUARIO = new Campesino();
    static Usuario userFound = null;
    public String u;
    /**
     * Creates new form GUI
     */
    public PagPrincipal() {
        initComponents();
                try {
            Image logo = ImageIO.read(PagPrincipal.class.getResource("/Classes/User/Recursos/minilogo2.png"));
            setIconImage(logo);
        } catch (IOException e) {
            e.printStackTrace();
        }
        setTitle("UNCampesino");
        bgestion.setVisible(false);
        bproductos.setVisible(false);
        banimales.setVisible(false);
        btareas.setVisible(false);
        bcultivos.setVisible(false);
        bProductos.setVisible(false);
        bGestorCompras.setVisible(false);
        bProductosTrabajador.setVisible(false);
        bAnimalesTrabajador.setVisible(false);
        bTareasTrabajador.setVisible(false);
        bCultivosTrabajador.setVisible(false);
        bCerrarSesion.setVisible(false);
        bIniciarSesion.setVisible(false);
    }
    private void centrarBoton(JToggleButton b,JToggleButton... buttons){
            for (JToggleButton button : buttons) {
        if (button != b) {
            button.setSelected(false);
        }
    }
    b.setSelected(true); // Asegura que el botón pasado como argumento esté seleccionado
    }
    private void cambiarPagina(JPanel p){
        p.setSize(780,640);
        p.setLocation(0,0);
        contenido.removeAll();
        contenido.add(p,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JPanel();
        bCerrarSesion = new javax.swing.JToggleButton();
        iniciarSesion = new javax.swing.JPanel();
        bIniciarSesion = new javax.swing.JToggleButton();
        menuCampesino = new javax.swing.JPanel();
        bgestion = new javax.swing.JToggleButton();
        bproductos = new javax.swing.JToggleButton();
        banimales = new javax.swing.JToggleButton();
        btareas = new javax.swing.JToggleButton();
        bcultivos = new javax.swing.JToggleButton();
        menuConsultor = new javax.swing.JPanel();
        bProductos = new javax.swing.JToggleButton();
        bGestorCompras = new javax.swing.JToggleButton();
        menuTrabajador = new javax.swing.JPanel();
        bProductosTrabajador = new javax.swing.JToggleButton();
        bAnimalesTrabajador = new javax.swing.JToggleButton();
        bCultivosTrabajador = new javax.swing.JToggleButton();
        bTareasTrabajador = new javax.swing.JToggleButton();
        contenido = new javax.swing.JPanel();
        bIngreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        bRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1300, 700));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(128, 151, 143));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/flor.png"))); // NOI18N
        logo.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

        panelPrincipal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

        cerrarSesion.setBackground(new java.awt.Color(128, 151, 143));
        cerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCerrarSesion.setBackground(new java.awt.Color(128, 151, 143));
        bCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bCerrarSesion.setForeground(new java.awt.Color(1, 1, 1));
        bCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/user.png"))); // NOI18N
        bCerrarSesion.setText("Cerrar Sesión");
        bCerrarSesion.setBorderPainted(false);
        bCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bCerrarSesion.setIconTextGap(20);
        bCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseExited(evt);
            }
        });
        bCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarSesionActionPerformed(evt);
            }
        });
        cerrarSesion.add(bCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 50));

        panelPrincipal.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 240, 70));

        iniciarSesion.setBackground(new java.awt.Color(128, 151, 143));
        iniciarSesion.setPreferredSize(new java.awt.Dimension(240, 60));
        iniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bIniciarSesion.setBackground(new java.awt.Color(128, 151, 143));
        bIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bIniciarSesion.setForeground(new java.awt.Color(1, 1, 1));
        bIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/user.png"))); // NOI18N
        bIniciarSesion.setText("Iniciar Sesión");
        bIniciarSesion.setBorderPainted(false);
        bIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bIniciarSesion.setIconTextGap(20);
        bIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bIniciarSesionMouseExited(evt);
            }
        });
        bIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesionActionPerformed(evt);
            }
        });
        iniciarSesion.add(bIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 50));

        panelPrincipal.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        menuCampesino.setBackground(new java.awt.Color(128, 151, 143));
        menuCampesino.setPreferredSize(new java.awt.Dimension(240, 640));
        menuCampesino.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgestion.setBackground(new java.awt.Color(128, 151, 143));
        bgestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bgestion.setForeground(new java.awt.Color(1, 1, 1));
        bgestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/user.png"))); // NOI18N
        bgestion.setText("Gestión de usuarios");
        bgestion.setBorderPainted(false);
        bgestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgestion.setIconTextGap(20);
        bgestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bgestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgestionMouseExited(evt);
            }
        });
        bgestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgestionActionPerformed(evt);
            }
        });
        menuCampesino.add(bgestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 240, 50));

        bproductos.setBackground(new java.awt.Color(128, 151, 143));
        bproductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bproductos.setForeground(new java.awt.Color(1, 1, 1));
        bproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/producto.png"))); // NOI18N
        bproductos.setText("Productos");
        bproductos.setBorderPainted(false);
        bproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bproductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bproductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bproductos.setIconTextGap(20);
        bproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bproductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bproductosMouseExited(evt);
            }
        });
        bproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bproductosActionPerformed(evt);
            }
        });
        menuCampesino.add(bproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 174, 240, 50));

        banimales.setBackground(new java.awt.Color(128, 151, 143));
        banimales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        banimales.setForeground(new java.awt.Color(1, 1, 1));
        banimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/animalesicon.png"))); // NOI18N
        banimales.setText("Animales");
        banimales.setBorderPainted(false);
        banimales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        banimales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        banimales.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        banimales.setIconTextGap(20);
        banimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banimalesMouseExited(evt);
            }
        });
        banimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banimalesActionPerformed(evt);
            }
        });
        menuCampesino.add(banimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 240, 50));

        btareas.setBackground(new java.awt.Color(128, 151, 143));
        btareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btareas.setForeground(new java.awt.Color(1, 1, 1));
        btareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/tarea.png"))); // NOI18N
        btareas.setText("Tareas");
        btareas.setBorderPainted(false);
        btareas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btareas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btareas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btareas.setIconTextGap(20);
        btareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btareasMouseExited(evt);
            }
        });
        btareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btareasActionPerformed(evt);
            }
        });
        menuCampesino.add(btareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        bcultivos.setBackground(new java.awt.Color(128, 151, 143));
        bcultivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bcultivos.setForeground(new java.awt.Color(1, 1, 1));
        bcultivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/trigo.png"))); // NOI18N
        bcultivos.setText("Cultivos");
        bcultivos.setBorderPainted(false);
        bcultivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bcultivos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bcultivos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bcultivos.setIconTextGap(20);
        bcultivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcultivosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcultivosMouseExited(evt);
            }
        });
        bcultivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcultivosActionPerformed(evt);
            }
        });
        menuCampesino.add(bcultivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 240, 50));

        panelPrincipal.add(menuCampesino, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 280));

        menuConsultor.setBackground(new java.awt.Color(128, 151, 143));
        menuConsultor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bProductos.setBackground(new java.awt.Color(128, 151, 143));
        bProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bProductos.setForeground(new java.awt.Color(1, 1, 1));
        bProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/producto.png"))); // NOI18N
        bProductos.setText("Productos");
        bProductos.setBorderPainted(false);
        bProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bProductos.setIconTextGap(20);
        bProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bProductosMouseExited(evt);
            }
        });
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        menuConsultor.add(bProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 240, 50));

        bGestorCompras.setBackground(new java.awt.Color(128, 151, 143));
        bGestorCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bGestorCompras.setForeground(new java.awt.Color(1, 1, 1));
        bGestorCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/tarea.png"))); // NOI18N
        bGestorCompras.setText("Gestor de compras");
        bGestorCompras.setBorderPainted(false);
        bGestorCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bGestorCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGestorCompras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bGestorCompras.setIconTextGap(20);
        bGestorCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bGestorComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bGestorComprasMouseExited(evt);
            }
        });
        bGestorCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestorComprasActionPerformed(evt);
            }
        });
        menuConsultor.add(bGestorCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 50));

        panelPrincipal.add(menuConsultor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 280));

        menuTrabajador.setBackground(new java.awt.Color(128, 151, 143));
        menuTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bProductosTrabajador.setBackground(new java.awt.Color(128, 151, 143));
        bProductosTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bProductosTrabajador.setForeground(new java.awt.Color(1, 1, 1));
        bProductosTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/producto.png"))); // NOI18N
        bProductosTrabajador.setText("Productos");
        bProductosTrabajador.setBorderPainted(false);
        bProductosTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bProductosTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bProductosTrabajador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bProductosTrabajador.setIconTextGap(20);
        bProductosTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bProductosTrabajadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bProductosTrabajadorMouseExited(evt);
            }
        });
        bProductosTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosTrabajadorActionPerformed(evt);
            }
        });
        menuTrabajador.add(bProductosTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 50));

        bAnimalesTrabajador.setBackground(new java.awt.Color(128, 151, 143));
        bAnimalesTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAnimalesTrabajador.setForeground(new java.awt.Color(1, 1, 1));
        bAnimalesTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/animalesicon.png"))); // NOI18N
        bAnimalesTrabajador.setText("Animales");
        bAnimalesTrabajador.setBorderPainted(false);
        bAnimalesTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bAnimalesTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAnimalesTrabajador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bAnimalesTrabajador.setIconTextGap(20);
        bAnimalesTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAnimalesTrabajadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAnimalesTrabajadorMouseExited(evt);
            }
        });
        bAnimalesTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnimalesTrabajadorActionPerformed(evt);
            }
        });
        menuTrabajador.add(bAnimalesTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 50));

        bCultivosTrabajador.setBackground(new java.awt.Color(128, 151, 143));
        bCultivosTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bCultivosTrabajador.setForeground(new java.awt.Color(1, 1, 1));
        bCultivosTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/trigo.png"))); // NOI18N
        bCultivosTrabajador.setText("Cultivos");
        bCultivosTrabajador.setBorderPainted(false);
        bCultivosTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCultivosTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCultivosTrabajador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bCultivosTrabajador.setIconTextGap(20);
        bCultivosTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCultivosTrabajadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCultivosTrabajadorMouseExited(evt);
            }
        });
        bCultivosTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCultivosTrabajadorActionPerformed(evt);
            }
        });
        menuTrabajador.add(bCultivosTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 50));

        bTareasTrabajador.setBackground(new java.awt.Color(128, 151, 143));
        bTareasTrabajador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bTareasTrabajador.setForeground(new java.awt.Color(1, 1, 1));
        bTareasTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/User/Recursos/tarea.png"))); // NOI18N
        bTareasTrabajador.setText("Tareas");
        bTareasTrabajador.setBorderPainted(false);
        bTareasTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bTareasTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bTareasTrabajador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bTareasTrabajador.setIconTextGap(20);
        bTareasTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bTareasTrabajadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTareasTrabajadorMouseExited(evt);
            }
        });
        bTareasTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTareasTrabajadorActionPerformed(evt);
            }
        });
        menuTrabajador.add(bTareasTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 50));

        panelPrincipal.add(menuTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 280));

        bIngreso.setText("Ingreso");
        bIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(202, 63, 65));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO A UNCampesino");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña");

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bRegistro.setText("Registro");
        bRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(bIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );

        panelPrincipal.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 780, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void bIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresoActionPerformed
        u=usuario.getText();
        String c=contraseña.getText();
        
        boolean registered=false;
             
        for (Usuario usuarioFor : USUARIO.leer()) {
                        if (usuarioFor.getUser().equals(u) && usuarioFor.getPasword().equals(c)) {
                            userFound = usuarioFor;
                            registered = true;
                            break; 
                        }
                    }
        if (registered){
             if (gestorUsuarios.controlVerDos.isConnected(userFound.getId(), gestorUsuarios.rol.leer().get(0).getId())){
                 bgestion.setVisible(true);
                 bproductos.setVisible(true);
                 banimales.setVisible(true);
                 btareas.setVisible(true);
                 bcultivos.setVisible(true);
                 bCerrarSesion.setVisible(true);
                
                 InicioCampesino inicioCampesino = new InicioCampesino(u);
                 cambiarPagina(inicioCampesino);
             }
             if (gestorUsuarios.controlVerDos.isConnected(userFound.getId(), gestorUsuarios.rol.leer().get(1).getId())){
                 bProductosTrabajador.setVisible(true);
                 bAnimalesTrabajador.setVisible(true);
                 bTareasTrabajador.setVisible(true);
                 bCultivosTrabajador.setVisible(true);
                 bCerrarSesion.setVisible(true);
                 
                 InicioTrabajador inicioTrabajador = new InicioTrabajador(u);
                 cambiarPagina(inicioTrabajador);
             }
             if (gestorUsuarios.controlVerDos.isConnected(userFound.getId(), gestorUsuarios.rol.leer().get(2).getId())){
                 bProductos.setVisible(true);
                 bGestorCompras.setVisible(true);
                 bCerrarSesion.setVisible(true);
                 
                 InicioConsultor inicioConsultor = new InicioConsultor(u);
                 cambiarPagina(inicioConsultor);
             } 
            JOptionPane.showMessageDialog(this, "Ingreso exitoso!");            
        }else{
            JOptionPane.showMessageDialog(this, "Ingreso fallido!\n"
                                                                         + "El usuario no existe.");
        }
    }//GEN-LAST:event_bIngresoActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void bgestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgestionActionPerformed
        centrarBoton(bgestion,bproductos,banimales,btareas,bcultivos);
        RegistroTrabajador registro=new RegistroTrabajador();
        cambiarPagina(registro);        // TODO add your handling code here:
    }//GEN-LAST:event_bgestionActionPerformed

    private void bproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bproductosActionPerformed
        centrarBoton(bproductos,bgestion,banimales,btareas,bcultivos);
        productosCRUD productosCRUD = new productosCRUD();
        cambiarPagina(productosCRUD);
    }//GEN-LAST:event_bproductosActionPerformed

    private void banimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banimalesActionPerformed
        centrarBoton(banimales,bproductos,bgestion,btareas,bcultivos);
        MenuAnimales menuAnimales = new MenuAnimales();
        cambiarPagina(menuAnimales);
    }//GEN-LAST:event_banimalesActionPerformed

    private void btareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btareasActionPerformed
        centrarBoton(btareas,bproductos,banimales,bgestion,bcultivos);
        MenuTareas menuTareas = new MenuTareas();
        cambiarPagina(menuTareas);
    }//GEN-LAST:event_btareasActionPerformed

    private void bcultivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcultivosActionPerformed
        centrarBoton(bcultivos,bproductos,banimales,btareas,bgestion);
        MenuCultivos menuCultivos = new MenuCultivos();
        cambiarPagina(menuCultivos);
    }//GEN-LAST:event_bcultivosActionPerformed

    private void bgestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgestionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgestionMouseClicked

    private void bgestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgestionMouseEntered
        bgestion.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bgestionMouseEntered

    private void bgestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgestionMouseExited
        bgestion.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bgestionMouseExited

    private void banimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banimalesMouseEntered
        banimales.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_banimalesMouseEntered

    private void banimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banimalesMouseExited
        banimales.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_banimalesMouseExited

    private void bcultivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcultivosMouseEntered
        bcultivos.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bcultivosMouseEntered

    private void bcultivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcultivosMouseExited
        bcultivos.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bcultivosMouseExited

    private void bproductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductosMouseEntered
        bproductos.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bproductosMouseEntered

    private void bproductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductosMouseExited
        bproductos.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bproductosMouseExited

    private void btareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btareasMouseEntered
        btareas.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_btareasMouseEntered

    private void btareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btareasMouseExited
        btareas.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_btareasMouseExited

    private void bCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseEntered
        bCerrarSesion.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bCerrarSesionMouseEntered

    private void bCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseExited
        bCerrarSesion.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bCerrarSesionMouseExited

    private void bCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarSesionActionPerformed
        dispose();
        PagPrincipal reinicio = new PagPrincipal(); 
        reinicio.setVisible(true);
    }//GEN-LAST:event_bCerrarSesionActionPerformed

    private void bRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistroActionPerformed
        bIniciarSesion.setVisible(true);
        RegistroConsultor registroConsultor = new RegistroConsultor();
        cambiarPagina(registroConsultor);
    }//GEN-LAST:event_bRegistroActionPerformed

    private void bTareasTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTareasTrabajadorActionPerformed
        centrarBoton(bTareasTrabajador,bAnimalesTrabajador, bCultivosTrabajador,bProductosTrabajador);
        MenuTareas menuTareas = new MenuTareas();
        cambiarPagina(menuTareas);
    }//GEN-LAST:event_bTareasTrabajadorActionPerformed

    private void bTareasTrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTareasTrabajadorMouseExited
        bTareasTrabajador.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bTareasTrabajadorMouseExited

    private void bTareasTrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTareasTrabajadorMouseEntered
        bTareasTrabajador.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bTareasTrabajadorMouseEntered

    private void bCultivosTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCultivosTrabajadorActionPerformed
        centrarBoton(bCultivosTrabajador,bAnimalesTrabajador,bTareasTrabajador,bProductosTrabajador);
        MenuCultivos menuCultivos = new MenuCultivos();
        cambiarPagina(menuCultivos);
    }//GEN-LAST:event_bCultivosTrabajadorActionPerformed

    private void bCultivosTrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCultivosTrabajadorMouseExited
        bCultivosTrabajador.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bCultivosTrabajadorMouseExited

    private void bCultivosTrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCultivosTrabajadorMouseEntered
        bCultivosTrabajador.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bCultivosTrabajadorMouseEntered

    private void bAnimalesTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnimalesTrabajadorActionPerformed
        centrarBoton(bAnimalesTrabajador, bCultivosTrabajador,bTareasTrabajador,bProductosTrabajador);
        MenuAnimales menuAnimales = new MenuAnimales();
        cambiarPagina(menuAnimales);
    }//GEN-LAST:event_bAnimalesTrabajadorActionPerformed

    private void bAnimalesTrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnimalesTrabajadorMouseExited
        bAnimalesTrabajador.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bAnimalesTrabajadorMouseExited

    private void bAnimalesTrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnimalesTrabajadorMouseEntered
        bAnimalesTrabajador.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bAnimalesTrabajadorMouseEntered

    private void bProductosTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosTrabajadorActionPerformed
        centrarBoton(bProductosTrabajador,bAnimalesTrabajador, bCultivosTrabajador,bTareasTrabajador);
        productosCRUD productosCRUD = new productosCRUD();
        cambiarPagina(productosCRUD);
    }//GEN-LAST:event_bProductosTrabajadorActionPerformed

    private void bProductosTrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosTrabajadorMouseExited
        bProductosTrabajador.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bProductosTrabajadorMouseExited

    private void bProductosTrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosTrabajadorMouseEntered
        bProductosTrabajador.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bProductosTrabajadorMouseEntered

    private void bGestorComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestorComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bGestorComprasActionPerformed

    private void bGestorComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGestorComprasMouseExited
        bGestorCompras.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bGestorComprasMouseExited

    private void bGestorComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGestorComprasMouseEntered
        bGestorCompras.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bGestorComprasMouseEntered

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
       ProductosCompra compra = new ProductosCompra();
        cambiarPagina(compra);
    }//GEN-LAST:event_bProductosActionPerformed

    private void bProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosMouseExited
        bProductos.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bProductosMouseExited

    private void bProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosMouseEntered
        bProductos.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bProductosMouseEntered

    private void bProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bProductosMouseClicked

    private void bIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMouseEntered
        bIniciarSesion.setBackground(new Color(153,181,171));
    }//GEN-LAST:event_bIniciarSesionMouseEntered

    private void bIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMouseExited
        bIniciarSesion.setBackground(new Color(128,151,143));
    }//GEN-LAST:event_bIniciarSesionMouseExited

    private void bIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesionActionPerformed
        dispose();
        PagPrincipal reinicio = new PagPrincipal(); 
        reinicio.setVisible(true);
    }//GEN-LAST:event_bIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        TemaUNCampesino.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bAnimalesTrabajador;
    private javax.swing.JToggleButton bCerrarSesion;
    private javax.swing.JToggleButton bCultivosTrabajador;
    private javax.swing.JToggleButton bGestorCompras;
    private javax.swing.JButton bIngreso;
    private javax.swing.JToggleButton bIniciarSesion;
    private javax.swing.JToggleButton bProductos;
    private javax.swing.JToggleButton bProductosTrabajador;
    private javax.swing.JButton bRegistro;
    private javax.swing.JToggleButton bTareasTrabajador;
    private javax.swing.JToggleButton banimales;
    private javax.swing.JToggleButton bcultivos;
    private javax.swing.JToggleButton bgestion;
    private javax.swing.JToggleButton bproductos;
    private javax.swing.JToggleButton btareas;
    private javax.swing.JPanel cerrarSesion;
    private javax.swing.JPanel contenido;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPanel iniciarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel menuCampesino;
    private javax.swing.JPanel menuConsultor;
    private javax.swing.JPanel menuTrabajador;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}

