/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MenuProductos;

import Classes.Product.Producto;
import Funcionalidades.GestorProductos;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Funcionalidades.GestorComprasQuaHeap;

/**
 *
 * @author CristianM
 */
public class ComprasCRUD extends javax.swing.JPanel {
    public static GestorProductos gestorProductos = new GestorProductos();
    /**
     * Creates new form productosCRUD
     */
    public GestorComprasQuaHeap listaQ= new GestorComprasQuaHeap();
    public ComprasCRUD() {
        initComponents();
    }
    private void cambiarPagina(JPanel p){
        p.setSize(780,640);
        p.setLocation(0,0);
        cont.removeAll();
        cont.add(p,BorderLayout.CENTER);
        cont.revalidate();
        cont.repaint();
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtNombreCRUD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecioCRUD = new javax.swing.JTextField();
        bAgregarProducto = new javax.swing.JButton();
        bMostrarProducto = new javax.swing.JButton();
        bMostrarProductos = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("nombre");
        cont.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jtNombreCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreCRUDActionPerformed(evt);
            }
        });
        cont.add(jtNombreCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, -1));

        jLabel3.setText("precio");
        cont.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        cont.add(jtPrecioCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, -1));

        bAgregarProducto.setText("Agregar Prod. a la cola");
        bAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarProductoActionPerformed(evt);
            }
        });
        cont.add(bAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        bMostrarProducto.setText("Mostrar un producto");
        bMostrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarProductoActionPerformed(evt);
            }
        });
        cont.add(bMostrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        bMostrarProductos.setText("Mostrar todos los productos");
        bMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarProductosActionPerformed(evt);
            }
        });
        cont.add(bMostrarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        bLimpiar.setText("Limpiar Campos");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        cont.add(bLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        cont.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 410));

        add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 640));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed

        jtNombreCRUD.setText("");
        jtPrecioCRUD.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarProductosActionPerformed
        StringBuilder sb = new StringBuilder();
        Producto[] datos=listaQ.ExtraerDatos();

        for(int i = 0; i<datos.length; i++){
            if(datos[i] != null){
                sb.append("Nombre: ").append(datos[i].getNombre()).append("\n");
                sb.append("Precio: ").append(Double.toString(datos[i].getPrecio())).append("\n");
                sb.append("\n");
            }
        }
        String resultado = sb.toString().trim();
        texto.setText(resultado);
    }//GEN-LAST:event_bMostrarProductosActionPerformed

    private void bMostrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarProductoActionPerformed
        StringBuilder sb = new StringBuilder();
        Producto dato=listaQ.ExtraerDato();
        if(listaQ.ExtraerDato() != null){
            sb.append("Nombre: ").append(dato.getNombre()).append("\n");
            sb.append("Precio: ").append(Double.toString(dato.getPrecio())).append("\n");
            sb.append("\n");
        }
        String resultado = sb.toString().trim();
        texto.setText(resultado);
    }//GEN-LAST:event_bMostrarProductoActionPerformed

    private void bAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarProductoActionPerformed
        listaQ.Insertar(Double.parseDouble(jtPrecioCRUD.getText()), jtNombreCRUD.getText());
        JOptionPane.showMessageDialog(this, "Producto agregado exitosamente!");
    }//GEN-LAST:event_bAgregarProductoActionPerformed

    private void jtNombreCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreCRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreCRUDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarProducto;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bMostrarProducto;
    private javax.swing.JButton bMostrarProductos;
    private javax.swing.JPanel cont;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtNombreCRUD;
    private javax.swing.JTextField jtPrecioCRUD;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
