/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MenuProductos;

import Classes.Product.Producto;
import Funcionalidades.GestorProductos;
import static GUI.MenuProductos.productosCRUD.gestorProductos;
import javax.swing.JOptionPane;

/**
 *
 * @author CristianM
 */
public class ProductosCompra extends javax.swing.JPanel {
    public double totalDinero = 0;
    /**
     * Creates new form ProductosCompra
     */
    public ProductosCompra() {
        initComponents();
        verColaApartados();
        verListaProductos();
        verTotalAcumulado();
    }
    
    public void verColaApartados(){
        String apartados = gestorProductos.colaProducto.toString();
        jtListaApartados.setText(apartados);       
    }
    
    public void verListaProductos(){
        StringBuilder sb = new StringBuilder();
            
            for(int i = 0; i<gestorProductos.listaProducto.length(); i++){
                if(gestorProductos.listaProducto != null){
                    sb.append("ID: ").append(gestorProductos.listaProducto.find(i).getId()).append("\n");               
                    sb.append("Nombre: ").append(gestorProductos.listaProducto.find(i).getNombre()).append("\n");               
                    sb.append("Precio: $").append(String.valueOf(gestorProductos.listaProducto.find(i).getPrecio())).append("\n"); 
                    sb.append("Cantidad: ").append(String.valueOf(gestorProductos.listaProducto.find(i).getCantidad())).append("\n"); 
                    sb.append("\n");
                }                      
            }
            String resultado = sb.toString().trim();
            jtListaProductos.setText(resultado);
    }
    
    public void verTotalAcumulado(){
        jtTotalDinero.setText("$" + String.valueOf(totalDinero));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        jtIdBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtIdVer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtCantidadVer = new javax.swing.JTextField();
        bUltimoApart = new javax.swing.JButton();
        bEliminarApartado = new javax.swing.JButton();
        bApartar = new javax.swing.JButton();
        jtIdApartar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtCantidadApartar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bEditarApar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaProductos = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListaApartados = new javax.swing.JTextArea();
        jtTotalDinero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setPreferredSize(new java.awt.Dimension(780, 640));
        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contenido.add(jtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 48, 620, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Compra de productos");
        contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 14, -1, -1));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        contenido.add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, 40));

        jLabel2.setText("id");
        contenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        contenido.add(jtIdVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, -1));

        jLabel3.setText("Nombre");
        contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        contenido.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, -1));

        jLabel4.setText("Precio");
        contenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        contenido.add(jtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 250, -1));

        jLabel5.setText("Cantidad");
        contenido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        contenido.add(jtCantidadVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 250, -1));

        bUltimoApart.setText("Ver último apartado");
        bUltimoApart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoApartActionPerformed(evt);
            }
        });
        contenido.add(bUltimoApart, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        bEliminarApartado.setText("Eliminar primer producto        ");
        bEliminarApartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarApartadoActionPerformed(evt);
            }
        });
        contenido.add(bEliminarApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        bApartar.setText("Apartar producto    ");
        bApartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApartarActionPerformed(evt);
            }
        });
        contenido.add(bApartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jtIdApartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdApartarActionPerformed(evt);
            }
        });
        contenido.add(jtIdApartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, -1));

        jLabel6.setText("Apartar producto");
        contenido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel7.setText("Ver producto");
        contenido.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel8.setText("id para apartar");
        contenido.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jtCantidadApartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCantidadApartarActionPerformed(evt);
            }
        });
        contenido.add(jtCantidadApartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 250, -1));

        jLabel9.setText("Cantidad para apartar");
        contenido.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        bEditarApar.setText("Editar cantidad más reciente");
        bEditarApar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarAparActionPerformed(evt);
            }
        });
        contenido.add(bEditarApar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel10.setText("Lista de todos los productos");
        contenido.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jtListaProductos.setColumns(20);
        jtListaProductos.setRows(5);
        jScrollPane1.setViewportView(jtListaProductos);

        contenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, 220));

        jLabel11.setText("Lista productos apartados");
        contenido.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jtListaApartados.setColumns(20);
        jtListaApartados.setRows(5);
        jScrollPane2.setViewportView(jtListaApartados);

        contenido.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 320, 220));
        contenido.add(jtTotalDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 130, -1));

        jLabel12.setText("Total acumulado");
        contenido.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bUltimoApartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoApartActionPerformed
         if(!gestorProductos.colaProducto.empty()){
            Producto producto = gestorProductos.verProductoApartado();
            jtIdVer.setText(producto.getId());
            jtNombre.setText(producto.getNombre());
            jtPrecio.setText(String.valueOf(producto.getPrecio()));           
            jtCantidadVer.setText(String.valueOf(producto.getCantidad())); 
        }else{
            JOptionPane.showMessageDialog(this, "No hay ningún producto apartado.");
        }                 
    }//GEN-LAST:event_bUltimoApartActionPerformed

    private void jtIdApartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdApartarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdApartarActionPerformed

    private void bEliminarApartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarApartadoActionPerformed
        if(!gestorProductos.colaProducto.empty()){
            totalDinero = totalDinero-(gestorProductos.verProductoApartado().getPrecio()*gestorProductos.verProductoApartado().getCantidad());
            gestorProductos.desapartarProducto();
            verColaApartados();
            verListaProductos();
            verTotalAcumulado();
            JOptionPane.showMessageDialog(this, "Producto desapartado exitosamente!");
        }else{
            JOptionPane.showMessageDialog(this, "No hay ningún producto apartado.");
        }       
    }//GEN-LAST:event_bEliminarApartadoActionPerformed

    private void jtCantidadApartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCantidadApartarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCantidadApartarActionPerformed

    private void bApartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApartarActionPerformed
        Producto producto = gestorProductos.buscarIdProducto(jtIdApartar.getText());
        if(producto != null){
            if(!jtCantidadApartar.getText().equals("")){
                if(producto.getCantidad() == 0){
                    JOptionPane.showMessageDialog(this, "No hay ninguna unidad de este producto");
                }else if(producto.getCantidad() < Integer.parseInt(jtCantidadApartar.getText())){
                    JOptionPane.showMessageDialog(this, "No hay suficientes unidades disponibles.\n"
                                                                                 + "Cantidad disponible: " + String.valueOf(producto.getCantidad()));   
                }else if(Integer.parseInt(jtCantidadApartar.getText()) < 0){
                    JOptionPane.showMessageDialog(this, "La cantidad ingresada es negativa, no se realizo apartado.");           
                }else{ 
                    totalDinero = totalDinero+ producto.getPrecio()*Integer.parseInt(jtCantidadApartar.getText()) ;
                    gestorProductos.apartarProducto(producto, Integer.parseInt(jtCantidadApartar.getText()));
                    JOptionPane.showMessageDialog(this, "Producto apartado con exito."
                                                                               + "\n  Precio: $" + producto.getPrecio() 
                                                                               + "\n  cantidad: " + jtCantidadApartar.getText() + " unidades"
                                                                               + "\n  Precio total: $" + producto.getPrecio()*Integer.parseInt(jtCantidadApartar.getText()));
                    verTotalAcumulado();
                    verColaApartados();
                    verListaProductos();
                }      
            }else{
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
            }
         }else{
            JOptionPane.showMessageDialog(this, "Producto no encontrado, no se realizo el apartado.");
        }
    }//GEN-LAST:event_bApartarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String id = jtIdBuscar.getText();
        Producto producto = gestorProductos.buscarIdProducto(id);
        
        if(producto != null){
            jtIdVer.setText(producto.getId());
            jtNombre.setText(producto.getNombre());
            jtPrecio.setText(String.valueOf(producto.getPrecio()));           
            jtCantidadVer.setText(String.valueOf(producto.getCantidad()));
            JOptionPane.showMessageDialog(this, "Producto encontrado exitosamente!");
        }else{
            jtIdVer.setText("");
            jtNombre.setText("");
            jtPrecio.setText("");           
            jtCantidadVer.setText("");
            JOptionPane.showMessageDialog(this, "Producto no encontrado!");
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEditarAparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarAparActionPerformed
        Producto producto = gestorProductos.verProductoApartado();
        if(producto != null){
        if(!jtCantidadApartar.getText().equals("")){
            if(Integer.parseInt(jtCantidadApartar.getText()) == producto.getCantidad()){
                JOptionPane.showMessageDialog(this, "Ha ingresado la misma cantidad, no se realizo edición!");
            }else if(producto.getCantidad() >= Integer.parseInt(jtCantidadApartar.getText()) && Integer.parseInt(jtCantidadApartar.getText()) >= 0){
                totalDinero = totalDinero-producto.getPrecio()*(producto.getCantidad()-Integer.parseInt(jtCantidadApartar.getText()));
                GestorProductos.editarCantidadUltimoApartado(Integer.parseInt(jtCantidadApartar.getText()));                
                JOptionPane.showMessageDialog(this, "Cantidad del producto apartado editada con exito!");
                verTotalAcumulado();
                verColaApartados();
                verListaProductos();
            }else if(Integer.parseInt(jtCantidadApartar.getText()) > producto.getCantidad()){
                JOptionPane.showMessageDialog(this, "La cantidad ingresada excede la cantidad del producto apartado, no se realizo edicion.");               
            }else if(Integer.parseInt(jtCantidadApartar.getText()) < 0){
                System.out.println("La cantidad ingresada es negativa, no se realizo edicion.");
            }                      
         }else{
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
         }
        }else{
            JOptionPane.showMessageDialog(this, "No hay ningún producto apartado.");
        }
    }//GEN-LAST:event_bEditarAparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApartar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditarApar;
    private javax.swing.JButton bEliminarApartado;
    private javax.swing.JButton bUltimoApart;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtCantidadApartar;
    private javax.swing.JTextField jtCantidadVer;
    private javax.swing.JTextField jtIdApartar;
    private javax.swing.JTextField jtIdBuscar;
    private javax.swing.JTextField jtIdVer;
    private javax.swing.JTextArea jtListaApartados;
    private javax.swing.JTextArea jtListaProductos;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtTotalDinero;
    // End of variables declaration//GEN-END:variables
}
