/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MenuCultivos;

import Classes.Cultivo.Hortaliza;
import Funcionalidades.GestorCultivos;
import Funcionalidades.GestorTareas;
import javax.swing.JOptionPane;

/**
 *
 * @author CristianM
 */
public class HortalizaCRUD extends javax.swing.JPanel {
    public static GestorCultivos gestorCultivos = new GestorCultivos();
    public static GestorTareas gestorTareas = new GestorTareas();
    /**
     * Creates new form CerealCRUD
     */
    public HortalizaCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtIdCereal = new javax.swing.JTextField();
        bBuscarCereal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtIdCRUD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNombreCRUD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtTipoCRUD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtNecesidadesCRUD = new javax.swing.JTextArea();
        bAgregarCereal = new javax.swing.JButton();
        bActualizarCereal = new javax.swing.JButton();
        bEliminarCereal = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jtIdCereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 620, -1));

        bBuscarCereal.setText("Buscar");
        bBuscarCereal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarCerealActionPerformed(evt);
            }
        });
        add(bBuscarCereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, 40));

        jLabel1.setText("id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jtIdCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdCRUDActionPerformed(evt);
            }
        });
        add(jtIdCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, -1));

        jLabel2.setText("nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jtNombreCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreCRUDActionPerformed(evt);
            }
        });
        add(jtNombreCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, -1));

        jLabel3.setText("tipo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jtTipoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTipoCRUDActionPerformed(evt);
            }
        });
        add(jtTipoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, -1));

        jLabel4.setText("lista de necesidades");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jtNecesidadesCRUD.setColumns(20);
        jtNecesidadesCRUD.setRows(5);
        jScrollPane1.setViewportView(jtNecesidadesCRUD);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 320));

        bAgregarCereal.setText("Agregar Hortaliza");
        bAgregarCereal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarCerealActionPerformed(evt);
            }
        });
        add(bAgregarCereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        bActualizarCereal.setText("Actualizar Hortaliza");
        bActualizarCereal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarCerealActionPerformed(evt);
            }
        });
        add(bActualizarCereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        bEliminarCereal.setText("Eliminar Hortaliza");
        bEliminarCereal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarCerealActionPerformed(evt);
            }
        });
        add(bEliminarCereal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        bLimpiar.setText("Limpiar Campos");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        add(bLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Gestion de hortalizas");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarCerealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarCerealActionPerformed
        Hortaliza hortaliza = gestorCultivos.buscarIdHortaliza(jtIdCereal.getText());
        if(hortaliza != null){
            jtIdCRUD.setText(hortaliza.getId());
            jtNombreCRUD.setText(hortaliza.getNombre());
            jtTipoCRUD.setText(hortaliza.getTipo());
            
            StringBuilder sb = new StringBuilder();
            
            for(int i = 0; i<hortaliza.getNecesidades().length(); i++){
                if(hortaliza.getNecesidades() != null){
                    sb.append("ID: ").append(hortaliza.getNecesidades().find(i).getId()).append("\n");               
                    sb.append("Descripción: ").append(hortaliza.getNecesidades().find(i).getDescripcion()).append("\n");               
                    sb.append("Completado: ").append(String.valueOf(hortaliza.getNecesidades().find(i).isCompletada())).append("\n"); 
                    sb.append("\n");
                }                      
            }
            String resultado = sb.toString().trim();
            jtNecesidadesCRUD.setText(resultado);
            
            JOptionPane.showMessageDialog(this, "Hortaliza encontrada exitosamente!");            
        }else{
            jtIdCRUD.setText("");
            jtNombreCRUD.setText("");
            jtTipoCRUD.setText("");
            jtNecesidadesCRUD.setText("");
            JOptionPane.showMessageDialog(this, "Hortaliza no encontrada!");  
        }
    }//GEN-LAST:event_bBuscarCerealActionPerformed

    private void jtIdCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdCRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdCRUDActionPerformed

    private void jtNombreCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreCRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreCRUDActionPerformed

    private void jtTipoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTipoCRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTipoCRUDActionPerformed

    private void bEliminarCerealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarCerealActionPerformed
        Hortaliza hortaliza = gestorCultivos.buscarIdHortaliza(jtIdCRUD.getText());
        if(hortaliza != null){
            gestorCultivos.eliminarHortaliza(jtIdCRUD.getText());
            jtIdCRUD.setText("");
            jtNombreCRUD.setText("");
            jtTipoCRUD.setText("");
            jtNecesidadesCRUD.setText("");
            JOptionPane.showMessageDialog(this, "Hortaliza eliminada exitosamente!");
        }else{
            JOptionPane.showMessageDialog(this, "Hortaliza no encontrada, no se realizo eliminación!");
        } 
    }//GEN-LAST:event_bEliminarCerealActionPerformed

    private void bAgregarCerealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarCerealActionPerformed
        gestorCultivos.agregarHortaliza(jtIdCRUD.getText(), jtNombreCRUD.getText(), gestorTareas.necesidadesCultivos);
        JOptionPane.showMessageDialog(this, "Hortaliza agregada exitosamente!");
    }//GEN-LAST:event_bAgregarCerealActionPerformed

    private void bActualizarCerealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarCerealActionPerformed
        Hortaliza hortaliza = gestorCultivos.buscarIdHortaliza(jtIdCRUD.getText());
        if(hortaliza != null){
            gestorCultivos.actualizarHortalizaNombre(hortaliza.getId(), jtNombreCRUD.getText());
            gestorCultivos.actualizarHortalizaNecesidades(hortaliza.getId(), gestorTareas.necesidadesCultivos);
            jtIdCRUD.setText("");
            jtNombreCRUD.setText("");
            jtTipoCRUD.setText("");
            jtNecesidadesCRUD.setText("");
            JOptionPane.showMessageDialog(this, "Hortaliza actualizada exitosamente!");
        }else{
            JOptionPane.showMessageDialog(this, "Hortaliza no encontrada, no se realizo actualización!");
        }    
    }//GEN-LAST:event_bActualizarCerealActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
            jtIdCRUD.setText("");
            jtNombreCRUD.setText("");
            jtTipoCRUD.setText("");
            jtNecesidadesCRUD.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarCereal;
    private javax.swing.JButton bAgregarCereal;
    private javax.swing.JButton bBuscarCereal;
    private javax.swing.JButton bEliminarCereal;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtIdCRUD;
    private javax.swing.JTextField jtIdCereal;
    private javax.swing.JTextArea jtNecesidadesCRUD;
    private javax.swing.JTextField jtNombreCRUD;
    private javax.swing.JTextField jtTipoCRUD;
    // End of variables declaration//GEN-END:variables
}
