/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MenuTareas;

import GUI.MenuProductos.*;
import Classes.Product.Producto;
import Funcionalidades.GestorProductos;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Funcionalidades.GestorComprasQuaHeap;
import Funcionalidades.*;
import Classes.Pendientes;
import Structures.*;
import java.util.List;
/**
 *
 * @author CristianM
 */
public class MenuPendientes extends javax.swing.JPanel {
    public static GestorProductos gestorProductos = new GestorProductos();
    /**
     * Creates new form productosCRUD
     */
    public GestorComprasQuaHeap listaQ= new GestorComprasQuaHeap();
    public GestorPendientes gestorPendiente=new GestorPendientes();
    public MenuPendientes() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        bAgregarPendiente = new javax.swing.JButton();
        bEliminarPendiente = new javax.swing.JButton();
        bMostrar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        bCompletarPendiente = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        cont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Descripción");
        cont.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescripcionActionPerformed(evt);
            }
        });
        cont.add(tDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 350, -1));

        jLabel3.setText("Prioridad");
        cont.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        cont.add(tPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 94, 220, -1));

        bAgregarPendiente.setText("Agregar Pendiente");
        bAgregarPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarPendienteActionPerformed(evt);
            }
        });
        cont.add(bAgregarPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        bEliminarPendiente.setText("Eliminar pendiente");
        bEliminarPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarPendienteActionPerformed(evt);
            }
        });
        cont.add(bEliminarPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        bMostrar.setText("Mostrar todos los pendientes");
        bMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarActionPerformed(evt);
            }
        });
        cont.add(bMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        bLimpiar.setText("Limpiar Campos");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        cont.add(bLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        texto.setColumns(20);
        texto.setRows(5);
        scroll.setViewportView(texto);

        cont.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 214, 264, 380));

        bCompletarPendiente.setText("Completar pendiente");
        bCompletarPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompletarPendienteActionPerformed(evt);
            }
        });
        cont.add(bCompletarPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        bBuscar.setText("Buscar pendiente");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        cont.add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gestor de pendientes");
        cont.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, 441, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed

        tDescripcion.setText("");
        tPrecio.setText("");
        texto.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarActionPerformed

            List<Pendientes> a=gestorPendiente.buscarPorPrioridad(0);
            StringBuilder sb = new StringBuilder();
            for (int i=0;i<a.size();i++){
                if(a.get(i) != null){
                    sb.append("Descripción: ").append(a.get(i).getDescription()).append("\n");
                    sb.append("Prioridad: ").append(Integer.toString(a.get(i).getPriority())).append("\n");
                    sb.append("\n");
                }
            }
        String resultado = sb.toString().trim();
        texto.setText(resultado);
    }//GEN-LAST:event_bMostrarActionPerformed

    private void bEliminarPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarPendienteActionPerformed
        List<Pendientes> a=gestorPendiente.buscarPorPrioridadExacta(Integer.parseInt(tPrecio.getText()));
        if (tDescripcion.getText().equals("")){
            for (int i=0;i<a.size();i++){
                gestorPendiente.eliminarPendiente(Integer.parseInt(tPrecio.getText()), a.get(i).getDescription());
            }
            JOptionPane.showMessageDialog(this, "Los pendientes con la prioridad "+ tPrecio.getText()+" han sido eliminados");
        }else{
            for (int i=0;i<a.size();i++){
                if(a.get(i) != null&&a.get(i).getDescription().equals(tDescripcion.getText())){
                    gestorPendiente.eliminarPendiente(Integer.parseInt(tPrecio.getText()), a.get(i).getDescription());
                    
                }
            }
            JOptionPane.showMessageDialog(this, "Los pendientes con la prioridad "+ tPrecio.getText()+" y la descripción "+ tDescripcion.getText()+" han sido eliminados");
        }
    }//GEN-LAST:event_bEliminarPendienteActionPerformed

    private void bAgregarPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarPendienteActionPerformed
        gestorPendiente.agregarPendiente(Integer.parseInt(tPrecio.getText()), tDescripcion.getText());
        JOptionPane.showMessageDialog(this, "Pendiente agregado exitosamente!");
    }//GEN-LAST:event_bAgregarPendienteActionPerformed

    private void tDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescripcionActionPerformed

    private void bCompletarPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompletarPendienteActionPerformed
        Pendientes o=new Pendientes();
        List<Pendientes> a=gestorPendiente.buscarPorPrioridadExacta(Integer.parseInt(tPrecio.getText()));
        for (int i=0;i<a.size();i++){
            if (a.get(i)==null){
                break;
            }
            if (a.get(i).getDescription().equals(tDescripcion.getText())){
              o=a.get(i);
              gestorPendiente.marcarCompletada(o);
              System.out.println(o.isCompletada());
              JOptionPane.showMessageDialog(this, "Pendiente completado!");
            }
            }
         if (o.getDescription()==null){
            JOptionPane.showMessageDialog(this, "Pendiente no encontrado!");
            }
    }//GEN-LAST:event_bCompletarPendienteActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        if (tDescripcion.getText().equals("")){
            List<Pendientes> a=gestorPendiente.buscarPorPrioridadExacta(Integer.parseInt(tPrecio.getText()));
            StringBuilder sb = new StringBuilder();
            for (int i=0;i<a.size();i++){
                if(a.get(i) != null){
                    sb.append("Descripción: ").append(a.get(i).getDescription()).append("\n");
                    sb.append("Prioridad: ").append(Integer.toString(a.get(i).getPriority())).append("\n");
                    sb.append("\n");
                }
            }
        String resultado = sb.toString().trim();
        texto.setText(resultado);
        }else{
            List<Pendientes> a=gestorPendiente.buscarPorPrioridadExacta(Integer.parseInt(tPrecio.getText()));
            
            StringBuilder sb = new StringBuilder();
            for (int i=0;i<a.size();i++){
                if(a.get(i) != null&&a.get(i).getDescription().equals(tDescripcion.getText())){
                    sb.append("Descripción: ").append(a.get(i).getDescription()).append("\n");
                    sb.append("Prioridad: ").append(Integer.toString(a.get(i).getPriority())).append("\n");
                    sb.append("\n");
                }
            }
        String resultado = sb.toString().trim();
        texto.setText(resultado);
        }
    }//GEN-LAST:event_bBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarPendiente;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCompletarPendiente;
    private javax.swing.JButton bEliminarPendiente;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bMostrar;
    private javax.swing.JPanel cont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tPrecio;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
